//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.11.14 at 02:49:33 PM GMT
//

package net.sf.mpxj.mspdi.schema;

import jakarta.xml.bind.annotation.adapters.XmlAdapter;

import java.math.BigDecimal;

@SuppressWarnings("all") public class Adapter2 extends XmlAdapter<String, BigDecimal>
{

   public BigDecimal unmarshal(String value)
   {
      return (jakarta.xml.bind.DatatypeConverter.parseDecimal(value));
   }

   public String marshal(BigDecimal value)
   {
      if (value == null)
      {
         return null;
      }
      return (jakarta.xml.bind.DatatypeConverter.printDecimal(value));
   }

}
