//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.08.02 at 09:18:52 PM BST
//

package net.sf.mpxj.planner.schema;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD) @XmlType(name = "") @XmlRootElement(name = "allocation") public class Allocation
{

   @XmlAttribute(name = "task-id", required = true) @XmlJavaTypeAdapter(NormalizedStringAdapter.class) protected String taskId;
   @XmlAttribute(name = "resource-id", required = true) @XmlJavaTypeAdapter(NormalizedStringAdapter.class) protected String resourceId;
   @XmlAttribute @XmlJavaTypeAdapter(NormalizedStringAdapter.class) protected String units;

   /**
    * Gets the value of the taskId property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public String getTaskId()
   {
      return taskId;
   }

   /**
    * Sets the value of the taskId property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setTaskId(String value)
   {
      this.taskId = value;
   }

   /**
    * Gets the value of the resourceId property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public String getResourceId()
   {
      return resourceId;
   }

   /**
    * Sets the value of the resourceId property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setResourceId(String value)
   {
      this.resourceId = value;
   }

   /**
    * Gets the value of the units property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public String getUnits()
   {
      return units;
   }

   /**
    * Sets the value of the units property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setUnits(String value)
   {
      this.units = value;
   }

}
